services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-api-top5-app
    container_name: laravel-api-top5-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    working_dir: /var/www

  mysql:
    image: mysql:8
    container_name: laravel-api-top5-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-api-top5-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-api-top5-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80" 
    depends_on:
      - mysql

volumes:
  mysql-data:
